/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AddRouteImport } from './routes/add'
import { Route as HomeRouteImport } from './routes/home'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as WorkWorkIdRouteImport } from './routes/work.$workId'

const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkWorkIdRoute = WorkWorkIdRouteImport.update({
  id: '/work/$workId',
  path: '/work/$workId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/add': typeof AddRoute
  '/home': typeof HomeRoute
  '/work/$workId': typeof WorkWorkIdRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/add': typeof AddRoute
  '/home': typeof HomeRoute
  '/work/$workId': typeof WorkWorkIdRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/add': typeof AddRoute
  '/home': typeof HomeRoute
  '/work/$workId': typeof WorkWorkIdRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/add' | '/home' | '/work/$workId' | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to: '/add' | '/home' | '/work/$workId' | '/work'
  id: '__root__' | '/add' | '/home' | '/work/$workId' | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AddRoute: typeof AddRoute
  HomeRoute: typeof HomeRoute
  WorkWorkIdRoute: typeof WorkWorkIdRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$workId': {
      id: '/work/$workId'
      path: '/work/$workId'
      fullPath: '/work/$workId'
      preLoaderRoute: typeof WorkWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AddRoute: AddRoute,
  HomeRoute: HomeRoute,
  WorkWorkIdRoute: WorkWorkIdRoute,
  WorkIndexRoute: WorkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
